---
title: "678 Project: Student Answer Correctness Prediction"
author: "Yuelin Jiang"
date: "12/7/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rstanarm)
library(lme4)
library(ggplot2)
library(arm)
library(performance)

```

## Import Data
```{r cars}
top <- read.csv('top15.csv')
colnames(top)

# transform time units from milliseconds to months
top$time <- top$time/31536000000*12
```
## EDA
```{r}
options(scipen=999)
options(digits = 2)
ggplot(data = top)+
  geom_histogram(aes(x = action_count), bins = 100)

ggplot(data = top)+
  geom_histogram(aes(x =round(time, digits = 4)), bins = 100)


ggplot(data = top)+
  geom_histogram(aes(x =round(std_accu, digits = 4)), bins = 100)

ggplot(data = top)+
  geom_histogram(aes(x =round(accu_q, digits = 4)), bins = 100)

```


## Data transformation
```{r pressure, echo=FALSE}

# make variables a factor var
class(top$prior_explain)
top$user_id <- as.factor(top$user_id)
top$part <- as.factor(top$part)
top$prior_explain <- as.factor(top$prior_explain)
top$content_id<- as.factor(top$content_id)
# is.factor(top$content_id)

# make cuts of continuous variables
top$action_cut <- cut(top$action_count, breaks = c(0, 7000, 15000))
# class(top$action_cut)
top$month_cut <- cut(top$time, breaks = c(0, 6, 12, 100))
top$std_cut <- cut(top$std_accu, breaks = c(0, 0.5, 0.75, 1))
top$q_accu_cut <- cut(top$accu_q, breaks = c(0, 0.5, 0.75, 1))

# class(top$std_cut)
```

```{r}
# basic log model
options(scipen=999)
complete_pooling <- glm(asw_correct ~ month_cut + q_accu_cut + prior_explain + part, 
                        family = binomial, data = top)

summary(complete_pooling)
```

```{r}
# add user_id as random effects, varying intercepts
user_pooled1 <- glmer(asw_correct ~ (1|user_id) + 
                        part + prior_explain +
                        month_cut + q_accu_cut, 
                      family = binomial, data = top)
summary(user_pooled1)
```


```{r}
# add content_id as random effect
user_pooled2 <- glmer(asw_correct ~ (1|user_id)+(1|part) 
                        + prior_explain +
                        month_cut + q_accu_cut, 
                      family = binomial, data = top)
summary(user_pooled2)
```


```{r}
user_stanpooled1 <- stan_glmer(asw_correct ~ (1|user_id) + 
                             part + prior_explain +
                             month_cut + q_accu_cut, 
                           family = binomial, data = top)
summary(user_stanpooled1, digits =4)
# added content_id as a multilevel
# user_stanpooled2 <- stan_glmer(asw_correct ~ (1|user_id) + (1|content_id)+
#                              part + prior_explain +
#                              month_cut + q_accu_cut, 
#                            family = binomial, data = top)
# summary(user_stanpooled2)
```

## Model check
```{r}
# residual check stan
plot(fitted(user_stanpooled1),resid(user_stanpooled1),pch=20, ylim = c(-2,2)) 
curve(sqrt(x),add=T)
title("Reisdual Plot of stan_glmer")
ylab("Observed - Estimated")
xlab("Estimated Values")

# check glmer
plot(fitted(user_pooled1),resid(user_pooled2),pch=20, ylim = c(-2,2)) 
curve(sqrt(x),add=T)

# bin residual
binnedplot(fitted(complete_pooling), resid(complete_pooling) )
binnedplot(fitted(user_pooled1), resid(user_pooled1) )
binnedplot(fitted(user_pooled2), resid(user_pooled2))
binnedplot(fitted(user_stanpooled1), resid(user_stanpooled1), main = "Binned Residual Plot of stan_glmer" )


```

```{r}
# posterior predict of stan_glmer
pp_check(user_stanpooled1)
class(user_stanpooled1)

pp_check(user_pooled1)

post.fit = posterior_predict(user_stanpooled1)
ppc_dens_overlay(y, post.fit)
```

```{r}
coefs <- data.frame(summary(user_stanpooled1)$coefficients)
  
output %>%
  kbl() %>%
  kable_classic(full_width = F, html_font = "Cambria") %>%
  footnote(general = "The table above is the summary output of the glmmTMB model.",              general_title = "Table 2: ")
```

